import { type Core } from "@strapi/strapi";
import { PLUGIN_ID } from "../../../admin/src/pluginId";
import Config from "../../../types/Config";

const notificationTitle: Record<
  | "staging-trigger"
  | "prod-trigger"
  | "trigger"
  | "staging-end"
  | "prod-end"
  | "end",
  string
> = {
  "staging-trigger": "Staging Workflow Triggered",
  "prod-trigger": "Production Workflow Triggered",
  trigger: "Workflow Triggered",
  "staging-end": "Staging Workflow Ended",
  "prod-end": "Production Workflow Ended",
  end: "Workflow Ended",
};

const emailAutogenerated =
  "<small>Questa email è stata generata automaticamente</small>";

const notificationBody = (
  workflowID: string,
  url: string,
): Record<
  "staging-trigger" | "prod-trigger" | "staging-end" | "prod-end",
  string
> => ({
  "staging-trigger": `È stata avviata l'esecuzione del workflow di staging (ID: ${workflowID})!<br/>È possibile accedere al pannello di amministrazione tramite l'URL ${url === "" ? "admin panel" : `<a href='${url}'>pannello di amministrazione</a>`} per controllare e gestire i workflow.<br/><br/>${emailAutogenerated}`,
  "prod-trigger": `È stata avviata l'esecuzione del workflow di produzione (ID: ${workflowID})!<br/>È possibile accedere al pannello di amministrazione tramite l'URL ${url === "" ? "admin panel" : `<a href='${url}'>pannello di amministrazione</a>`} per controllare e gestire i workflow.<br/><br/>${emailAutogenerated}`,
  "staging-end": `L'esecuzione del workflow di staging (ID: ${workflowID}) è stata completata!<br/>È possibile accedere a ${url === "" ? "pannello di amministrazione" : `<a href='${url}'>pannello di amministrazione</a>`} per verificarne il risultato.<br/><br/>${emailAutogenerated}`,
  "prod-end": `L'esecuzione del workflow di produzione (ID: ${workflowID}) è stata completata!<br/>È possibile accedere al pannello di amministrazione tramite l'URL ${url === "" ? "pannello di amministrazione" : `<a href='${url}'>pannello di amministrazione</a>`} per verificarne il risultato.<br/><br/>${emailAutogenerated}`,
});

const notificationsService = ({ strapi }: { strapi: Core.Strapi }) => ({
  async send(
    event: "staging-trigger" | "prod-trigger" | "staging-end" | "prod-end",
  ) {
    try {
      if (
        ![
          "staging-trigger",
          "prod-trigger",
          "staging-end",
          "prod-end",
        ].includes(event)
      ) {
        return { success: false, err: "Invalid Event" };
      }

      const workflowID: Config["workflowID"] = strapi
        .plugin(PLUGIN_ID)
        .config("workflowID");
      const staging: Config["staging"] = strapi
        .plugin(PLUGIN_ID)
        .config("staging");
      const notifications: Config["notifications"] = strapi
        .plugin(PLUGIN_ID)
        .config("notifications");
      const url: string = strapi.config.get("server.url");

      if (!notifications || !notifications.enabled) {
        return { enabled: false, success: true };
      }

      const emails = (
        await strapi
          .documents(`plugin::${PLUGIN_ID}.email-for-notifications`)
          .findMany({ sort: "email:asc" })
      ).map((doc) => doc.email);

      if (emails.length > 0) {
        strapi.plugin("email").services.email.send({
          to: emails,
          subject: notificationTitle[event],
          html: notificationBody(
            event === "staging-trigger" || event === "staging-end"
              ? (staging?.workflowID ?? "")
              : workflowID,
            url,
          )[event],
        });
      }

      return { enabled: true, success: true };
    } catch (err: any) {
      return { success: false, err };
    }
  },
  async getEmails() {
    try {
      const emails = (
        await strapi
          .documents(`plugin::${PLUGIN_ID}.email-for-notifications`)
          .findMany({ sort: "email:asc" })
      ).map((doc) => doc.email);
      return { success: true, emails };
    } catch (err: any) {
      return { success: false, err };
    }
  },
  async addEmail(newEmail: string) {
    try {
      strapi
        .documents(`plugin::${PLUGIN_ID}.email-for-notifications`)
        .create({ data: { email: newEmail.toLowerCase() } });
      return { success: true };
    } catch (err: any) {
      return { success: false, err };
    }
  },
  async deleteEmail(emailToDelete: string) {
    try {
      const docToDelete = await strapi
        .documents(`plugin::${PLUGIN_ID}.email-for-notifications`)
        .findFirst({
          filters: {
            email: {
              $eqi: emailToDelete,
            },
          },
        });

      if (docToDelete) {
        strapi
          .documents(`plugin::${PLUGIN_ID}.email-for-notifications`)
          .delete({ documentId: docToDelete.documentId });
      }

      return { success: true };
    } catch (err: any) {
      return { success: false, err };
    }
  },
});

export default notificationsService;
