name: Setup Node.JS
description: Setup Node.JS

inputs:
  package_manager:
    description: 'The package manager to use'
    default: 'npm'
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup node
      uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
      with:
        node-version-file: '.node-version'
        cache: ${{ inputs.package_manager }}
