name: deploy
description: Deploy on AWS S3 Bucket

inputs:
  environment:
    description: 'The environment target'
    required: true
  iam_role:
    description: 'The IAM Role to use to perform the deploy'
    required: true
  bucket:
    description: "The AWS S3 Bucket's name selected as destination"
    required: true
  cloudfront_distribution_id:
    description: 'The ID of the Cloudfront distribution to invalidate'
    required: true
  aws_region:
    description: 'The AWS region selected'
    required: false
    default: 'eu-south-1'
  strapi_api_token:
    description: 'The Token to communicate with Strapi'
    required: false
  strapi_api_base_url:
    description: 'The API URL to communicate with Strapi'
    required: false
  cdn_path:
    description: 'The CDN bucket S3 URL'
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab

    - name: Setup Node.JS
      uses: ./.github/actions/setup-node

    - name: Configure NextJS cache
      uses: actions/cache@88522ab9f39a2ea568f7027eddc7d8d8bc9d59c8 # v3.3.1
      with:
        path: ${{ github.workspace }}/apps/nextjs-website/.next/cache
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

    - name: Install dependencies
      shell: bash
      run: npm ci

    - name: Compile packages
      shell: bash
      run: npm run compile

    - name: Build static website
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        NEXT_TELEMETRY_DISABLED: "1"
        STRAPI_API_TOKEN: ${{ inputs.strapi_api_token }}
        STRAPI_API_BASE_URL: ${{ inputs.strapi_api_base_url }}
        CDN_PATH: ${{ inputs.cdn_path }}
      shell: bash
      run: npm run build -w nextjs-website

    - name: Configure AWS Credentials
      uses: ./.github/actions/configure-aws-credentials
      with:
        aws_region: ${{ inputs.aws_region }}
        role_to_assume: ${{ inputs.iam_role }}

    - name: Deploy to S3 Bucket
      shell: bash
      run: aws s3 sync ./apps/nextjs-website/out s3://${{ inputs.bucket }} --delete

    - name: Create AWS Cloudfront Invalidation
      shell: bash
      run: aws cloudfront create-invalidation --distribution-id ${{ inputs.cloudfront_distribution_id }} --paths "/*" # At the moment we invalidate all the paths