/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import seo from "@strapi-community/plugin-seo/strapi-admin";
import colorPicker from "@strapi/plugin-color-picker/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import collectionExporter from "strapi-plugin-collection-exporter/strapi-admin";
import previewButton from "strapi-plugin-preview-button/strapi-admin";
import staticDeploy from "../../src/plugins/static-deploy/./dist/admin/index.mjs";
import rollback from "../../src/plugins/rollback/./dist/admin/index.mjs";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.ts";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    seo: seo,
    "color-picker": colorPicker,
    "users-permissions": usersPermissions,
    "collection-exporter": collectionExporter,
    "preview-button": previewButton,
    "static-deploy": staticDeploy,
    rollback: rollback,
  },
});
