/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import seo from "@strapi/plugin-seo/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import previewButton from "strapi-plugin-preview-button/strapi-admin";
import staticDeploy from "strapi-plugin-static-deploy/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

import customisations from "../../src/admin/app.ts";

renderAdmin(document.getElementById("strapi"), {
  customisations,

  plugins: {
    seo: seo,
    "users-permissions": usersPermissions,
    "preview-button": previewButton,
    "static-deploy": staticDeploy,
  },
});
