import { MediaResourcesSection } from '@/lib/fetch/types/PageSection';
import { SiteWidePageData } from '@/lib/fetch/siteWideSEO';

export const mediaResourcesMockData: MediaResourcesSection & SiteWidePageData =
  {
    __component: 'sections.media-resources',
    theme: 'light',
    sectionID: 'media-resources',
    title: 'Risorse per i media',
    items: [
      {
        title: 'Documenti su IO',
        label: 'Scarica il documento',
        thumbnail: {
          url: 'https://via.placeholder.com/400',
          alternativeText: null,
          width: 400,
          height: 300,
          mime: 'image/png',
          formats: null,
        },
        resource: {
          url: 'https://via.placeholder.com/400',
          alternativeText: null,
          width: 400,
          height: 300,
          mime: 'image/png',
          formats: null,
        },
      },
      {
        title: 'Messaggi',
        label: 'Scarica immagine',
        thumbnail: {
          url: 'https://via.placeholder.com/400',
          alternativeText: null,
          width: 400,
          height: 300,
          mime: 'image/png',
          formats: null,
        },
        resource: {
          url: 'https://via.placeholder.com/400',
          alternativeText: null,
          width: 400,
          height: 300,
          mime: 'image/png',
          formats: null,
        },
      },
      {
        title: 'Pagamenti',
        label: 'Scarica il documento',
        thumbnail: {
          url: 'https://via.placeholder.com/400',
          alternativeText: null,
          width: 400,
          height: 300,
          mime: 'image/png',
          formats: null,
        },
        resource: {
          url: 'https://via.placeholder.com/400',
          alternativeText: null,
          width: 400,
          height: 300,
          mime: 'image/png',
          formats: null,
        },
      },
      {
        title: 'SEND',
        label: 'Scarica immagine',
        thumbnail: {
          url: 'https://via.placeholder.com/400',
          alternativeText: null,
          width: 400,
          height: 300,
          mime: 'image/png',
          formats: null,
        },
        resource: {
          url: 'https://via.placeholder.com/400',
          alternativeText: null,
          width: 400,
          height: 300,
          mime: 'image/png',
          formats: null,
        },
      },
      {
        title: 'Servizi',
        label: 'Scarica immagine',
        thumbnail: {
          url: 'https://via.placeholder.com/400',
          alternativeText: null,
          width: 400,
          height: 300,
          mime: 'image/png',
          formats: null,
        },
        resource: {
          url: 'https://via.placeholder.com/400',
          alternativeText: null,
          width: 400,
          height: 300,
          mime: 'image/png',
          formats: null,
        },
      },
      {
        title: 'App IO',
        label: 'Scarica immagine',
        thumbnail: {
          url: 'https://via.placeholder.com/400',
          alternativeText: null,
          width: 400,
          height: 300,
          mime: 'image/png',
          formats: null,
        },
        resource: {
          url: 'https://via.placeholder.com/400',
          alternativeText: null,
          width: 400,
          height: 300,
          mime: 'image/png',
          formats: null,
        },
      },
      {
        title: 'Logo e brand manual',
        label: 'Scarica il manuale',
        thumbnail: {
          url: 'https://via.placeholder.com/400',
          alternativeText: null,
          width: 400,
          height: 300,
          mime: 'image/png',
          formats: null,
        },
        resource: {
          url: 'https://via.placeholder.com/400',
          alternativeText: null,
          width: 400,
          height: 300,
          mime: 'image/png',
          formats: null,
        },
      },
    ],
    locale: 'it',
    defaultLocale: 'it',
    themeVariant: 'SEND',
  };
