import { PageSwitchSection } from '@/lib/fetch/types/PageSection';
import { SiteWidePageData } from '@/lib/fetch/siteWideSEO';

export const pageSwitchMockData: PageSwitchSection & SiteWidePageData = {
  __component: 'sections.page-switch',
  theme: 'light',
  themeVariant: 'SEND',
  title: 'Scopri le funzionalità',
  subtitle: 'Esplora i diversi scenari d’uso con esempi pratici',
  locale: 'it',
  defaultLocale: 'it',
  pages: [
    {
      id: 1,
      buttonText: 'Cittadini',
      sections: [
        {
          __component: 'sections.editorial',
          title: 'IO per i cittadini',
          titleTag: 'h2',
          eyelet: null,
          body: 'Un unico punto di accesso per comunicare con la PA.',
          theme: 'light',
          pattern: 'dots',
          width: 'standard',
          reversed: false,
          sectionID: null,
          image: {
            url: 'https://notifichedigitali.pagopa.it/static/images/pa-infoblock-5.png',
            alternativeText: null,
            width: 800,
            height: 600,
            mime: 'image/png',
            formats: null,
          },
          mobileImage: {
            url: 'https://notifichedigitali.pagopa.it/static/images/pi-infoblock-1.png',
            alternativeText: null,
            width: 400,
            height: 300,
            mime: 'image/png',
            formats: null,
          },
          ctaButtons: [],
          storeButtons: null,
        },
        {
          __component: 'sections.cards',
          theme: 'light',
          title: 'Servizi offerti',
          subtitle: 'Panoramica',
          body: 'Ecco cosa puoi fare con IO.',
          ctaButtons: [],
          bottomCTA: null,
          sectionID: null,
          textPosition: 'left',
          items: [
            {
              title: 'Notifiche digitali',
              text: 'Ricevi messaggi importanti dalla PA',
              icon: null,
              label: null,
              links: [],
            },
            {
              title: 'Pagamenti',
              text: 'Paga direttamente dall’app',
              icon: null,
              label: null,
              links: [],
            },
          ],
        },
        {
          __component: 'sections.banner-link',
          theme: 'light',
          sectionID: null,
          sections: [
            {
              title: 'Hai bisogno di aiuto?',
              body: 'Contattaci via email all’indirizzo supporto@io.italia.it',
              icon: null,
              ctaButtons: [
                {
                  text: 'Scrivici',
                  href: 'mailto:supporto@io.italia.it',
                  variant: 'contained',
                  size: 'medium',
                  icon: null,
                },
              ],
            },
          ],
        },
      ],
    },
    {
      id: 2,
      buttonText: 'Enti',
      sections: [
        {
          __component: 'sections.editorial',
          title: 'IO per gli enti',
          titleTag: 'h2',
          eyelet: null,
          body: 'Un canale unico e sicuro per raggiungere i cittadini.',
          theme: 'light',
          pattern: 'dots',
          width: 'standard',
          reversed: true,
          sectionID: null,
          image: {
            url: 'https://notifichedigitali.pagopa.it/static/images/pa-infoblock-5.png',
            alternativeText: null,
            width: 800,
            height: 600,
            mime: 'image/png',
            formats: null,
          },
          mobileImage: {
            url: 'https://notifichedigitali.pagopa.it/static/images/pi-infoblock-1.png',
            alternativeText: null,
            width: 400,
            height: 300,
            mime: 'image/png',
            formats: null,
          },
          ctaButtons: [],
          storeButtons: null,
        },
        {
          __component: 'sections.cards',
          theme: 'light',
          title: 'Funzionalità per enti',
          subtitle: 'Cosa puoi fare',
          body: 'Strumenti digitali al servizio della tua amministrazione.',
          ctaButtons: [],
          bottomCTA: null,
          sectionID: null,
          textPosition: 'left',
          items: [
            {
              title: 'Invio notifiche',
              text: 'Comunicazioni puntuali e tracciabili',
              icon: null,
              label: null,
              links: [],
            },
          ],
        },
      ],
    },
  ],
};
