name: Check PR branch up to date

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
jobs:

  check_branch_up_to_date:
    name: Verify branch is up to date
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
        with:
          fetch-depth: '0'

      - name: Check PR branch is updated
        uses: ./.github/actions/branch-up-to-date
