name: Dry Build

permissions:
  contents: read

on:
  pull_request:
    paths:
      - 'apps/nextjs-website/**'
      - '.github/workflows/dry_build.yaml'

jobs:
  dry_build:
    name: Run Dry Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.JS
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Compile packages
        run: npm run compile

      - name: Run Dry Build
        run: npm run build:dry
        working-directory: apps/nextjs-website
