name: Notify of Production Workflow End

on:
  workflow_run:
    workflows: ["Promote Website to Production"]
    types:
      - completed

jobs:
  call-api:
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ github.event.workflow_run.inputs.environment }}
    steps:
      - name: Call Strapi API (${{ matrix.environment }})
        shell: bash
        run: |
          curl -X POST "${{ vars.STRAPI_URL }}/static-deploy/notify-workflow-end" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.WORKFLOW_NOTIFICATIONS_BEARER_TOKEN }}" \
            -d '{"event": "prod-end"}'