name: Enrich Pull Request

on: pull_request

jobs:

  add_labels:
    name: Add labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Add size label
        uses: pagopa/github-actions-template/check-pr-size@241d9bfcaa2a623cb78a2d993716d761af158c0c # v1.6.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          min_size: 200
          max_size: 600
