name: Enrich Pull Request

on: pull_request

jobs:

  add_labels:
    name: Add labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest

    steps:
      - name: Add size label
        uses: pagopa/github-actions-template/check-pr-size@241d9bfcaa2a623cb78a2d993716d761af158c0c # v1.6.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          ignored_files: 'package-lock.json, docs/'
          min_size: 200
          max_size: 600

      - name: Add labels
        uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594 # v4.3.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labels.yaml
          sync-labels: true

  add_assignee:
    name: Add assignee
    runs-on: ubuntu-latest

    steps:
      - name: Assign PR
        uses: kentaro-m/auto-assign-action@3e986bf9c274729de0d85191da42484917883328 # v1.2.5
        with:
          configuration-path: '.github/auto_assign.yaml'
